#!/bin/bash

#ManagerV2Ray

clear

#barra
barra () {
cd /etc/newadm && bash menu --barra
}

v2file="/etc/v2ray/config.json"

#colors
red="\033[1;31m"
blue="\033[1;34m"
green="\033[1;32m"
yellow="\033[1;33m"
white="\033[0m"
cyan="\033[1;36m"
azul="\033[44m"

#color
color () {
[[ -e "/etc/newadm/idioma" ]] && id=$(cat /etc/newadm/idioma) || id=es
COLOR=$1
echo -e "${COLOR}$(source trans -b es:${id} "${@:2}")\033[0m"
}
#trans
fun_trans () {
TEXT=$1
[[ -e "/etc/newadm/idioma" ]] && ide=$(cat /etc/newadm/idioma) || ide=es
retorno=$(source trans -b es:${ide} "$TEXT")
}

#color 2
color2 () {
COLOR=$1
echo -e "\033[${COLOR}${@:2}\033[0m"
}

menu () {
barra
echo -e "${yellow} ADMINISTRADOR V2RAY ${green}[NEW-ADM+] ${white}"
barra
echo -e "${green}[1] ${red}> ${cyan}Crear un nuevo acceso${white}"
echo -e "${green}[2] ${red}> ${cyan}Modificar el Host${white}"
echo -e "${green}[3] ${red}> ${cyan}Ver Configuracion Actual${white}"
echo -e "${green}[4] ${red}> ${cyan}Detener Servicio V2ray${white}"
echo -e "${green}[5] ${red}> ${cyan}Iniciar Servicio V2ray${white}"
echo -e "${green}[6] ${red}> ${red}> ${cyan}Eliminar ID${white}"
echo -e "${green}[7] ${red}> ${cyan}Agregar ID especifico${white}"
echo -e "${green}[8] ${red}> ${cyan}Cambiar Puerto${white}"
echo -e "${green}[9] ${red}> ${cyan}Comprobar Estado de V2ray${white}"
echo -e "${green}[10] ${red}> ${cyan}Arreglar ID${white}"
echo -e "${green}[11] ${red}> ${cyan}Reiniciar V2Ray${white}"
echo -e "${green}[0] ${red}> ${cyan}Salir${white}"
barra
#echo EN CASO DE EQUIVOCARSE, SALIR DEL SCRIPT CON CTRL + c 
#barra
echo 
#read -p "Seleccionar una opción: " opcion
color ${white} "Seleccione una opción: 》" && read opcion
}
menu

if [ $opcion = 1 ]; then
    cd
    cd v2ray/
    ./v2ctl uuid > userID
    ls
    cat userID
    userID=$(cat userID)
    clear
    sed -i '9a\            { "id": "tu-id-aqui-xd", "alterId":aID, "level":1 }\' config.json
    sed -i '10s/$/,/' config.json
    sed -i "s/tu-id-aqui-xd/$userID/g" config.json
    read -p "Introduce un AlterID: " altID
    sed -i "s/aID/$altID/g" config.json
    echo -------
    echo ID: $userID
    echo -------
    echo AlterID: $altID
    echo -------
    read -p "Presiona una tecla para continuar..." tend
    cd
    sh v2m.sh
fi

if [ $opcion = 2 ]; then
    clear
    cd
    echo Tu Host actual es:
    echo
    sed '/host/!d' ${v2file}
    read -p "INTRODUCE EL HOST ACTUAL: " hostact
    sed -i "s/$hostact/acaelhost/g" ${v2file}
    read -p "INTRODUCE EL NUEVO HOST: " newhost
    sed -i "s/acaelhost/$newhost/g" ${v2file}
    clear
    echo ---------------------------
    echo HOST CAMBIADO CORRECTAMENTE
    echo ---------------------------
    echo NUEVO HOST $newhost
    echo ---------------------------
    read -p "PRESIONA UNA TECLA PARA CONTINUAR..." tend
    clear
    cd
    sh v2m.sh
fi

if [ $opcion = 3 ]; then
    cd
    sed '/id/!d' ${v2file}
    sed '/host/!d' ${v2file}
    sed '/port/!d' ${v2file}
    sed '/patch/!d' ${v2file}
    sed '/protocol/!d' ${v2file}
    echo
    read -p "PRESIONA UNA TECLA PARA CONTINUAR..." t
    sh v2m.sh
fi

if [ $opcion = 4 ]; then
    clear
    tmux kill-session -t v0
    clear
    echo SERVICIO V2RAY DETENIDO
    sleep 2
    cd 
    sh v2m.sh
fi

if [ $opcion = 5 ]; then
    clear
    cd
    cd v2ray/ && tmux new-session -d -s v0 './v2ray' && cd
    echo SERVICIO V2RAY INICIADO
    sleep 2
    cd
    sh v2m.sh
fi

if [ $opcion = 6 ]; then
    clear
    echo ¡IMPORTANTE! NO ELIMINAR EL ID GENERADO EN LA INSTALACION
    echo
    echo LO IDENTIFICAS PORQUE NO TIENE UNA COMA AL FINAL DE LA LINEA
    echo
    echo A CONTINUACION TENDRAS UNA LISTA CON LOS ID EXISTENTES
    sleep 5
    cd
    sed '/id/!d' ${v2file}
    read -p "INTRODUZCA EL ID QUE DESEA ELIMINAR: " iddel
    cd v2ray/
    sed -i "/$iddel/d" ./config.json
    cd
    sh v2m.sh
fi

if [ $opcion = 7 ]; then
    clear
    cd
    cd v2ray/
    read -p "INTRODUCE EL NUEVO ID: " idcustom
    sed -i '9a\            { "id": "tu-id-aqui-xd", "alterId":aID, "level":1 }\' config.json
    sed -i '10s/$/,/' config.json
    sed -i "s/tu-id-aqui-xd/$idcustom/g" config.json
    read -p "Introduce un AlterID del 1 al 1000: " altID
    sed -i "s/aID/$altID/g" config.json
    echo -------
    echo ID: $idcustom
    echo -------
    echo AlterID: $altID
    echo -------
    read -p "Presiona una tecla para continuar..." tend
    cd
    sh v2m.sh
fi

if [ $opcion = 8 ]; then
    clear
    cd
    read -p "INTRODUZCA EL NUEVO PUERTO: " puerto
    cd v2ray/
    sed -i '/port/d' ./config.json
    sed -i "5a\      \"port\": $puerto," ./config.json
    cd
    sh v2m.sh
fi

if [ $opcion = 9 ]; then
    cd
    cd v2ray/
    tmux ls > statustmux
    sed -i 's/: 1.*//' statustmux
    cat statustmux
    ls
    statmux=$(cat statustmux)
    if [ $statmux = v0 ]; then
    clear
    echo V2Ray ENCENDIDO
    sleep 4
    cd
    sh v2m.sh
    else
    clear
    echo V2Ray APAGADO
    sleep 4
    cd
    sh v2m.sh
    fi
fi

if [ $opcion = 10 ]; then
    cd
    sed '/id/!d' ${v2file}
    echo
    read -p "INTRODUZCA EL ULTIMO DE LA LISTA (SI APARECEN VARIOS) O EL UNICO ALTERID: " rid
    sed -i "s/$rid, \"level\":1 },/$rid, \"level\":1 }/g" ${v2file}
    cd
    sh v2m.sh
fi

if [ $opcion = 11 ]; then
    clear
    echo REINICIANDO V2RAY
    tmux kill-session -t v0
    cd
    cd v2ray/
    tmux new-session -d -s v0 './v2ray'
    cd
    echo ------------
    sleep 3
    echo V2RAY ENCENDIDO
    sleep 3
    sh v2m.sh
fi

if [ $opcion = 0 ]; then
    exit
fi

exit
